application: signalrecorder
version: 1
runtime: python
api_version: 1

handlers:
- url: /upload
  script: upload.py

- url: /map.*
  static_dir: map
  
- url: /gheat.*
  script: gheatae/app_main.py

- url: /.*
  script: landing.py
