application: signalrecorder
version: 1
runtime: python
api_version: 1

handlers:
- url: /upload
  script: upload.py
  
- url: /gheat.*
  script: gheatae/app_main.py

- url: /s
  static_dir: static

- url: /.*
  script: landing.py
